---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install apache2 webserver on ansible nodes
    apt: 
      name: apache2
      state: present
    when: ansible_os_family== "Debian"
  - name:
    service:
      name: apache2
      state: started    
    when: ansible_os_family== "Debian"