---
- name: add tomacat admin user
  template:
       src: templates/mytomuser.j2
       dest: /opt/tomcat/conf/tomcat-users.xml
     
- name: change context file
  template: 
       src: templates/mytomcontext.j2 
       dest: /opt/tomcat/webapps/manager/META-INF/context.xml
- nmae: change host xml file
  template: 
       src: templates/myhost.j2
       dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml
